= Innledning [[Innledning]]

Formålet med standarden er å legge til rette for utveksling av beskrivelser av datasett med høy verdi (på engelsk __High Value Dataset__), forkortet til HVD. https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32023R013898[HVD-gjennomføringsforordningen &#x29C9;, window="_blank", role="ext-link"] som p.t. er under vurdering i EØS-EFTA, spesifiserer HVD innen følgende seks tematiske områder: geodata, jordobservasjoner og miljø, meteorologi, statistikk, selskaper og eierskap, mobilitet. Forordningen stiller også et minimumskrav til metadata i beskrivelser av HVD. 

Denne standarden supplerer https://data.norge.no/specification/dcat-ap-no[Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO) &#x29C9;, window="_blank", role="ext-link"], og beskriver hvordan DCAT-AP-NO brukes til å tilfredsstille minimumskrav til metadata for HVD spesifisert i ovennevnte forordningen. 

Se ellers formålet med https://data.norge.no/specification/dcat-ap-no/#Innledning[DCAT-AP-NO  &#x29C9;, window="_blank", role="ext-link"] som også gjelder for denne standarden. 

