= Forvaltningsregime [[Forvaltningsregime]]

Dersom det oppdages mindre feil i standarden (stavefeil, upresis formulering, lenkefeil etc.), vil ikke korrigering av disse utløse en ny versjon. Disse korrigeringene skal imidlertid dokumenteres.

Utarbeidelse av nye versjoner av denne standarden initieres av Digitaliseringsdirektoratet. Den primære kilden til nye versjoner vil være endringer i EU-standarden https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/[DCAT-AP High Value Datasets &#x29C9;, window="_blank", role="ext-link"] som denne standarden baseres på, og/eller https://data.norge.no/specification/dcat-ap-no[DCAT-AP-NO &#x29C9;, window="_blank", role="ext-link"] som denne supplerer. 

Digitaliseringsdirektoratet vil i forbindelse med nye versjoner av ovennevnte bakenforliggende standarder avgjøre om endringene er så store at det bør nedsettes en egen arbeidsgruppe bestående av relevante aktører, eller om revisjonen kan utføres av Digitaliseringsdirektoratet selv. Forslaget til ny hovedversjon (engelsk "_major release_") sendes uansett på høring. De innkomne høringskommentarene behandles hos Digitaliseringsdirektoratet, og resulterer i et forslag som oversendes https://www.digdir.no/standarder/arkitektur-og-standardiseringsradet/3918[Arkitektur- og standardiseringsrådet &#x29C9;, window="_blank", role="ext-link"]. I lys av anbefalinger fra rådet vil Digitaliseringsdirektoratet fatte beslutning om den reviderte hovedversjonen av standarden skal være gjeldende eller forkastes.

Gjeldende og eventuelle tidligere versjoner av standarden skal være tilgjengelige på Digitaliseringsdirektoratets nettsider, slik at det er enkelt å finne ut når tidligere versjoner var gyldige, og hvilke endringer som er foretatt mellom to versjoner.
