name: build adocs and publish to Github-pages

on:
  push:
    branches:
    - develop
    paths:
    - docs/**

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 0

    - name: Update submodules to latest main
      run: |
          git submodule foreach --recursive git fetch origin
          git submodule foreach --recursive git checkout origin/main

    - name: Build html
      id: adocbuild_html
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

    - name: Build pdf
      id: adocbuild_pdf
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor-pdf -D docs -o files/hvd-dcat-ap-no.pdf -a lang=nb docs/main.adoc"
      continue-on-error: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
