name: build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  upload-files-to-production:
    name: Upload specification to static-rdf-server
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: |
        asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc
      program_pdf: |
        asciidoctor-pdf -D docs -o files/hvd-dcat-ap-no.pdf -a lang=nb docs/main.adoc
      program_pdf_continue_on_error: true
      files: |
        docs/index.html text/html nb
        docs/files/hvd-dcat-ap-no.pdf application/pdf nb files/hvd-dcat-ap-no.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/datasett-distribusjon-datatjeneste.png image/png nb images/datasett-distribusjon-datatjeneste.png
        docs/images/HVD-DCAT-AP-NO-forenklet-fremstilling.png image/png nb images/HVD-DCAT-AP-NO-forenklet-fremstilling.png
        docs/images/Klassen-Datasett.png image/png nb images/Klassen-Datasett.png
        docs/images/Klassen-Datasettserie.png image/png nb images/Klassen-Datasettserie.png
        docs/images/Klassen-Datatjeneste.png image/png nb images/Klassen-Datatjeneste.png
        docs/images/Klassen-Distribusjon.png image/png nb images/Klassen-Distribusjon.png
      host: https://data.norge.no
      ontology: hvd-dcat-ap-no
      ontology-type: specification
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
